apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qotm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.1
        ports:
        - name: http-api
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qotm
  name: qotm
spec:
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
  selector:
    app: qotm
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qotm-ingress
  labels:
    app: qotm
spec:
  backend:
    serviceName: qotm
    servicePort: 80